services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--accesslog=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=admin@nohost.network"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "38.175.195.19:443:443"
#      - "100.64.0.2:8080:8080"
    restart: unless-stopped
    volumes:
      - "../secrets/traefik/letsencrypt:/letsencrypt"
      - "../secrets/traefik/passwords:/passwords"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
    - external

networks:
  external:
    external: true
